Updates to fetching Stats time interval data
wordpress-mobile/WordPressKit-iOS pull request #712
Opened 2024-01-30 12:04 UTC by staskus

https://github.com/wordpress-mobile/WordPress-iOS/issues/22459

Related PR: 

### Description

This PR contains two additions:

1. Include an optional `unit` parameter when fetching StatsTimeIntervalData which determines the granularity of returned data for a given period
2. Add `StatsTotalsSummaryData` type for fetching totals for `stats/summary` 

### Testing Details

ℹ Please replace this with a clear and concise description of the steps required to validate this pull request.

---

- [ ] Please check here if your pull request includes additional test coverage.
- [ ] I have considered if this change warrants release notes and have added them to the appropriate section in the `CHANGELOG.md` if necessary.

2024-01-30 20:37 UTC, crazytonyli requested changes, later dismissed
Do you mind adding some unit tests for the new feature?

2024-01-30 20:37 UTC, crazytonyli commented on CHANGELOG.md
> +- `StatsTimeIntervalData` now accepts an optional `unit: StatsPeriodUnit` parameter that allows to describe the granularity of data fetched for a given period. [#712]
This changelog should go to the "Unreleased" section. Changing "Unreleased" to a released version is part of the release process.

https://github.com/wordpress-mobile/WordPressKit-iOS/blob/24b055e8066ddfe69a4557c8db7529dbf0537ae0/CHANGELOG.md?plain=1#L7-L11

2024-01-31 08:12 UTC, staskus commented
Thanks for the review, @crazytonyli!

2024-02-13 17:11 UTC, guarani approved these changes
Looks good and I ran the test locally.

2024-02-14 09:12 UTC, merged